admins: []
forwards:
- source: MS21_Dump
  dest:
  - -1001555690227
  offset: 31097
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.0
plugins:
  filter:
    text:
      blacklist: []
